<?php

namespace AppBundle\Repository;

/**
 * NotificationDeviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationDeviceRepository extends \Doctrine\ORM\EntityRepository
{
}
