<?php

namespace AppBundle\Repository;

/**
 * PoiUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoiUserRepository extends \Doctrine\ORM\EntityRepository
{
}
